name: MagneX CI (sycl)

on:
  push:
    # branches: [development]
    paths-ignore:
      - Docs
      - README.rst
      - license.txt

  pull_request:
    branches: [development]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-sycl
  cancel-in-progress: true

jobs:
  Build-And-Test-SYCL:
    name: oneAPI SYCL - SUNDIALS ${{matrix.sundials}} - AMReX ${{matrix.amrex_mode}}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sundials: [OFF, ON]
        amrex_mode: [internal, external_src]

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Free up disk space
      uses: ./.github/actions/free-space-ubuntu

    - name: Dependencies
      run: |
        if [ "${{matrix.amrex_mode}}" == "external_src" ]; then
          git clone https://github.com/AMReX-Codes/amrex.git _deps/amrex-src
          git clone https://github.com/LLNL/sundials.git _deps/sundials-src
          _deps/amrex-src/.github/workflows/dependencies/dependencies_dpcpp.sh
        else
          .github/workflows/dependencies/documentation.sh
        fi

    - name: Install CCache
      run: |
        if [ "${{matrix.amrex_mode}}" == "external_src" ]; then
          _deps/amrex-src/.github/workflows/dependencies/dependencies_ccache.sh
        else
          sudo apt-get update
          sudo apt-get install -y ccache
        fi

    - name: Set Up Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-

    - name: Build & Install
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=250M
        export CCACHE_DEPEND=1
        ccache -z

        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e
        mkdir build
        cd build
        if [ "${{matrix.amrex_mode}}" == "external_src" ]; then
          cmake .. \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/MagneX/install \
            -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DMagneX_MPI:BOOL=ON \
            -DMagneX_COMPUTE:STRING=SYCL \
            -DMagneX_SUNDIALS:BOOL=${{matrix.sundials}} \
            -DMagneX_amrex_src:PATH=${{github.workspace}}/_deps/amrex-src \
            -DMagneX_sundials_src:PATH=${{github.workspace}}/_deps/sundials-src \
            -DCMAKE_C_COMPILER=$(which icx) \
            -DCMAKE_CXX_COMPILER=$(which icpx) \
            -DCMAKE_CXX_STANDARD=17
        else
          cmake .. \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/MagneX/install \
            -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DMagneX_MPI:BOOL=ON \
            -DMagneX_COMPUTE:STRING=SYCL \
            -DMagneX_SUNDIALS:BOOL=${{matrix.sundials}} \
            -DCMAKE_C_COMPILER=$(which icx) \
            -DCMAKE_CXX_COMPILER=$(which icpx) \
            -DCMAKE_CXX_STANDARD=17
        fi
        make -j 2 2>&1 | tee -a ${{runner.workspace}}/build-output-${{matrix.sundials}}-${{matrix.amrex_mode}}.txt;

        ccache -s
        du -hs ~/.cache/ccache

    - name: Report
      run: |
        egrep "warning:|error:" ${{runner.workspace}}/build-output-${{matrix.sundials}}-${{matrix.amrex_mode}}.txt \
          | egrep -v "_deps/amrex" | egrep -v "lto-wrapper: warning:" | sort | uniq \
          | awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > ${{runner.workspace}}/build-output-warnings-${{matrix.sundials}}-${{matrix.amrex_mode}}.txt
        cat ${{runner.workspace}}/build-output-warnings-${{matrix.sundials}}-${{matrix.amrex_mode}}.txt
        export return=$(tail -n 1 ${{runner.workspace}}/build-output-warnings-${{matrix.sundials}}-${{matrix.amrex_mode}}.txt | awk '{print $2}')
        exit ${return}
